In [3]:
%ls

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 58B3-92B1

 C:\K8_Python_data_science\K8_Python_data_science 디렉터리

2024-11-12  오후 12:50    <DIR>          .
2024-11-12  오후 12:50    <DIR>          ..
2024-11-12  오후 12:50    <DIR>          .ipynb_checkpoints
2024-11-12  오후 12:13             2,639 1112예제.ipynb
2024-11-12  오후 12:49            20,004 AIProg_chap01.ipynb
2024-11-12  오전 11:56    <DIR>          PythonDataScienceHandbook-master
2024-11-12  오전 11:57                24 README.md
2024-11-12  오후 12:41               617 Untitled.ipynb
               4개 파일              23,284 바이트
               4개 디렉터리  417,015,566,336 바이트 남음


In [4]:
%run myscript.py

Exception: File `'myscript.py'` not found.

In [5]:
import numpy 

In [6]:
!pip install numpy

In [7]:
import numpy as np

In [8]:
x=4

In [9]:
x='abc' #동적 typing

In [10]:
result=0
for i in range(100):
    result += i

In [11]:
l=[1,2,3.0,'abc','hong']

In [12]:
l

[1, 2, 3.0, 'abc', 'hong']

In [13]:
l=list(range(10))

In [14]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
r=range(10)

In [16]:
r

range(0, 10)

In [17]:
r?

Type:        range
String form: range(0, 10)
Length:      10
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).

In [18]:
l?

Type:        list
String form: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Length:      10
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [19]:
list? #iterable 객체가 와야함

SyntaxError: invalid syntax (2595654227.py, line 1)

In [20]:
import array
L=list(range(10))
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np

In [22]:
n=np.array([1,2,3,4])

In [23]:
n

array([1, 2, 3, 4])

In [24]:
np.array([3.14, 4,2,3]) #같은 타입이 되게끔 정수를 실수로 바꿈 numpy=고정타입

array([3.14, 4.  , 2.  , 3.  ])

In [25]:
np.array([3.14, 4.  , 2.  , 3. ], dtype='float32' )

array([3.14, 4.  , 2.  , 3.  ], dtype=float32)

In [26]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.arange(0,20,2) # 꼭 기억할 것 자주 사용!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.linspace(0,1,5) # 0~1 구간에 5개 간격

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.random.normal(0,1,(3,3)) #(평균, 표준편차(3*3 배열)) 난수로 채운 배열 만들기

array([[ 0.68396099, -1.70561717,  0.72807745],
       [-1.00996231,  0.77741364, -0.06287457],
       [ 0.1294268 , -1.77632496,  0.91099706]])

In [32]:
np.random.randint(0,10,(3,3)) #[0,10] 구간의 임의의 정수로 채운 3*3 배열 만들기

array([[3, 0, 9],
       [7, 9, 3],
       [2, 3, 8]])

In [33]:
np.random.seed(0) #seed값을 주면 random이라도 항상 같은 값이 나옴
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [34]:
x1
x2
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [35]:
x1 #1차원 배열

array([5, 0, 3, 3, 7, 9])

In [36]:
x2 #2차원 배열

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [37]:
x3 #3차원 배열

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [38]:
print("x3 ndim: ", x3.ndim)

x3 ndim:  3


In [39]:
print("x3 shape: ", x3.shape)

x3 shape:  (3, 4, 5)


In [40]:
x1[-1] #배열의 마지막 숫자

9

In [41]:
x2[-1] #마지막 배열

array([1, 6, 7, 7])

In [42]:
x2[-2] #마지막에서 두번째 배열

array([7, 6, 8, 8])

In [43]:
x2[-2,-1] #마지막에서 두번째 배열 마지막 숫자

8

In [44]:
x1[1:5:2] #[start,end,step]

array([0, 3])

In [45]:
x=np.arange(10)

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[3:9:2]

array([3, 5, 7])

In [48]:
x[::-2] #step이 마이너스면 거꾸로 

array([9, 7, 5, 3, 1])

In [49]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [50]:
l = [1, 2, 3, 4, 5, 6, 7]
l2 = l[:2:-1] ## 슬라이싱은 사본을 만든다 l2를 수정하면 l은 변경되지 않는다.

In [51]:
l2

[7, 6, 5, 4]

In [56]:
l2[0] = 77

In [57]:
l

[1, 2, 3, 4, 5, 6, 7]

In [58]:
l2

[77, 6, 5, 4]

In [59]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [66]:
x2_1 = x2[::-1,::-1].copy() ## 사본이 아니라 view를 제공

In [67]:
x2_1

array([[99,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]])

In [63]:
x2_1[0,0] = 99

In [64]:
x2_1

array([[99,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5,  3]])

In [68]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
grid = grid.reshape((3,3)) # 1차원 배열을 2차원 배열로 변환.

In [72]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
grid.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [74]:
grid[np.newaxis,:]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [82]:
x = np.array([1,2,3])

In [84]:
x[np.newaxis,:] # 2차원

array([[1, 2, 3]])

In [85]:
x[:,np.newaxis] # 2차원 각 각의 열

array([[1],
       [2],
       [3]])